services:
  protuario_pg:
    image: postgres:14
    container_name: protuario_pg
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - protuario_network
networks:
  protuario_network:
    driver: bridge

volumes:
  db_data: